import type { Request, Response } from "express";
import * as applicationService from "../services/application.service.js";
import { streamPortalPdf } from "../services/pdf.service.js";

export async function list(req: Request, res: Response) {
  res.json(await applicationService.listApplications(req.query as any));
}

export async function updateStatus(req: Request, res: Response) {
  res.json(await applicationService.updateApplicationStatus(String(req.params.id), req.body.status, req.body.remarks));
}

export async function acknowledgement(req: Request, res: Response) {
  streamPortalPdf(res, "Application Acknowledgement", [`Application ID: ${req.params.id}`, "Status: Submitted", "Generated by Centralized Examination Portal"]);
}
