import { Router } from "express";
import { authRoutes } from "./auth.routes.js";
import { examRoutes } from "./exam.routes.js";
import { applicationRoutes } from "./application.routes.js";
import { ruleRoutes } from "./rule.routes.js";
import { dashboardRoutes } from "./dashboard.routes.js";
import { prisma } from "../config/prisma.js";
import { streamPortalPdf } from "../services/pdf.service.js";

export const apiRoutes = Router();

apiRoutes.use("/auth", authRoutes);
apiRoutes.use("/dashboard", dashboardRoutes);
apiRoutes.use("/examinations", examRoutes);
apiRoutes.use("/applications", applicationRoutes);
apiRoutes.use("/eligibility-rules", ruleRoutes);

apiRoutes.get("/notifications", async (_req, res) => res.json(await prisma.notification.findMany({ orderBy: { createdAt: "desc" }, take: 20 })));
apiRoutes.get("/audit-logs", async (_req, res) => res.json(await prisma.auditLog.findMany({ orderBy: { createdAt: "desc" }, take: 100 })));
apiRoutes.get("/hall-tickets/:id.pdf", async (req, res) => streamPortalPdf(res, "Hall Ticket", [`Hall Ticket ID: ${req.params.id}`, "QR Code: embedded in production renderer", "Reporting Time: 08:30 AM"]));
apiRoutes.get("/results/:id/score-card.pdf", async (req, res) => streamPortalPdf(res, "Score Card", [`Result ID: ${req.params.id}`, "Qualified: Yes", "Generated by Centralized Examination Portal"]));
