import { Router } from "express";
import { authRoutes } from "./auth.routes.js";
import { examRoutes } from "./exam.routes.js";
import { applicationRoutes } from "./application.routes.js";
import { ruleRoutes } from "./rule.routes.js";
import { dashboardRoutes } from "./dashboard.routes.js";
import { stateRoutes } from "./state.routes.js";
import { candidateRoutes } from "./candidate.routes.js";
import { hallTicketRoutes } from "./hall-ticket.routes.js";
import { questionRoutes } from "./question.routes.js";
import { prisma } from "../config/prisma.js";
import { streamPortalPdf } from "../services/pdf.service.js";

export const apiRoutes = Router();

apiRoutes.use("/auth", authRoutes);
apiRoutes.use("/dashboard", dashboardRoutes);
apiRoutes.use("/examinations", examRoutes);
apiRoutes.use("/applications", applicationRoutes);
apiRoutes.use("/eligibility-rules", ruleRoutes);
apiRoutes.use("/state", stateRoutes);
apiRoutes.use("/candidate", candidateRoutes);
apiRoutes.use("/hall-tickets", hallTicketRoutes);
apiRoutes.use("/questions", questionRoutes);

apiRoutes.get("/candidate-public/live-exams", async (_req, res, next) => {
  try {
    res.json(await import("../services/exam.service.js").then((service) => service.listLiveExams()));
  } catch (error) {
    next(error);
  }
});
apiRoutes.get("/candidate-public/active-phase", async (req, res, next) => {
  try {
    res.json(await import("../services/exam.service.js").then((service) => service.getCandidatePhaseSnapshot(req.query.examId as string | undefined)));
  } catch (error) {
    next(error);
  }
});
apiRoutes.get("/notifications", async (_req, res) => res.json(await prisma.notification.findMany({ orderBy: { createdAt: "desc" }, take: 20 })));
apiRoutes.get("/audit-logs", async (_req, res) => res.json(await prisma.auditLog.findMany({ orderBy: { createdAt: "desc" }, take: 100 })));
apiRoutes.get("/results/:id/score-card.pdf", async (req, res) => streamPortalPdf(res, "Score Card", [`Result ID: ${req.params.id}`, "Qualified: Yes", "Generated by Centralized Examination Portal"]));
